import "./globals.css";
import "@repo/primitives/styles.css";
import { SocketProvider } from "@/context/socket";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Handler } from "@/components/handler";
import { cn } from "@repo/primitives/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="en">
			<body className={cn(inter.className, "dark")}>
				<SocketProvider>
					<Handler />
					{children}
				</SocketProvider>
			</body>
		</html>
	);
}
